### ISSUE TITLE
Crash when attempting to move ZynEcho

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#15]
Steps to reproduce:
1. synthpod_jack -g
2. Select ZynEcho (from zynaddsubfx-3.0.2)
3. Point on it with mouse and Ctrl + left mouse click
4. synthpod_jack prints "bye" and exits with exit code 0

It shouldn't exit on an attempt to move the plugin.

**Comment by ventosus** [comment]
I cannot reproduce this.

Does the DSP side crash or the UI side? The two run in separate processes. If the DSP side is started together with the UI (-g) and the UI closes (or crashes), the DSP side automatically closes, too.

Can you try to start the DSP side and the UI separately?

    synthpod_alsa -G ...

    synthpod_ui

So we know which side actually crashes?

**Comment by yurivict** [comment]
I run ```synthpod_jack -g```.  I don't have ALSA available on my OS.
It actually doesn't crash, onoy says 'bye' and exits.

When I tun ```synthpod_jack -G```, it opens the window.  ```synthpod_ui``` just hangs when run at the same time.

**Comment by ventosus** [comment]
Well, doesn't matter whether synthpod_jack/alsa/dummy, they all work the same.

\synthpod_jack/alsa/dummy -G\ should *not* open any UI, it should strictly run as server, e.g. as command line app, if you run it in a terminal.

Will check in an FreeBSD VM asap. DSP and UI communicate via a lock-free ringbuffer in shared memory, maybe FreeBSD needs some special handling, there...

**Comment by yurivict** [comment]
The patches in this shar archive make it build easily: https://bz-attachments.freebsd.org/attachment.cgi?id=185136

**Comment by ventosus** [comment]
Found the culprit, qsort_r has totally different semantics on BSD than on GNU/Linux.
Needs some preprocesser macro magic :(

Ah, and the (-G) command line argument is broken, too

**Comment by yurivict** [comment]
I think last two args are swapped on BSD.
```
#if defined(__linux__)
                qsort_r(hash->nodes, hash->size, sizeof(void *), cmp, data);
#elif defined(__FreeBSD__)
                qsort_r(hash->nodes, hash->size, sizeof(void *), data, cmp);
#else
#   error "Please define qsort_r on this platform"
#endif
```

**Comment by ventosus** [comment]
Fixed in https://github.com/OpenMusicKontrollers/synthpod/commit/ac39807d84a5fe5ca19cfcc4c40746a2d9815307

**Comment by yurivict** [comment]
You forgot OpenBSD. qsort_r has BSD semantics there too: http://man.openbsd.org/FreeBSD-11.0/qsort.3

```#if ... defined(__OpenBSD__)```

Other different places are likely to be like FreeBSD, rather than linux.
